name: "Junctek Battery Monitor"
description: "Reads your Junctek Battery Monitor Values via BLE"
version: "1.0.68"
slug: "junctek"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
host_dbus: true

hassio_api: true
homeassistant_api: true
hassio_role: admin

options:
  macaddress: 
  battery capacity: 400
  voltage: 48
  log_level: info

schema:
  macaddress: str?
  battery capacity: int
  voltage: int
  log_level: list(debug|info|warning|error)

services:
  - mqtt:need

map:
  - share:rw
  
image: "ghcr.io/tsjippy/{arch}-junctek"